### ISSUE TITLE
Adding existing Wallet

### ISSUE THREAD

**Issue by hscanlan** [ricmoo/ethers-meow#10]
I notice the Account.json creates a new account, but how do we add an existing account?

**Comment by ricmoo** [comment]
If your existing account is a Geth Wallet, Parity Wallet or Crowdsale wallet it will work fine. I do not currently have support for Mnemonics, and plan to add it, but if you are comfortable with node, you can use my ethers.js library (`npm install ethers`) and use:

```
/home/ricmoo> node
> var ethers = require('ethers')
> var mnemonic = 'abuse boss fly bamboo banana pencil owner cage cash clinic time actress'
> var wallet = ethers.Wallet.fromMnemonic(mnemonic)
> wallet.encrypt('password1').then(function(json) { console.log(json); })
// This may take 5-10 seconds to complete
 {"address":"c833deaeb3394afdfc193b52c452bd8d61e2afb3","id":"c95963f3-8637-4220-b0d3-0e77f5330a21","version":3,"Crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"33516671bd90d0d52bbeb89f19153608"},"ciphertext":"405bcce2927084adb38e31d0a13c59ae10450b1a2c6e9e9c2568212bc5110c89","kdf":"scrypt","kdfparams":{"salt":"0c98e2fb3ebfc0c560d191a1f5e242dd501c4bd0de3d6e8d356b86a2cc2cfc8a","n":131072,"dklen":32,"p":1,"r":8},"mac":"c6939d7a85b4cb2e34567510cfcdfbd01c870f7435fd09a5eb8a922153553cdd"}}
```

You can then paste that JSON into a new file and use it. Basically you just need any standard JSON wallet. The above converts a Mneomic wallet into a JSON wallet.

Make sure you clear your node REPL history afterwards.

Otherwise, it will still likely be a few days before I get around to adding mnemonic phrases to the ethers-cli library, at which point ethers-meow will support it too.

**Comment by hscanlan** [comment]
Awesome, thank you for the quick feedback!!!

**Comment by ricmoo** [comment]
One other option is to crate a new wallet and *gift* all your kitties; but at the current gas prices, that might be cost-prohibitive. :)

**Comment by hscanlan** [comment]
Gotchal Ya my primary goal is to be able to transfer from Wallet to Another .. I was hoping your transfer code would work as such ..

**Comment by ricmoo** [comment]
Yupp, transfers work peachy. I use this script for all my CK needs. :)
